spring.application.name=discografia
server.port=8081


spring.data.mongodb.uri=mongodb+srv://Alejandro_cabello:Iplacex2026@cluster-spring.wbmgo0e.mongodb.net/discografica-db?retryWrites=true&w=majority
spring.data.mongodb.database=discografica-db


spring.mongodb.uri=mongodb+srv://Alejandro_cabello:Iplacex2026@cluster-spring.wbmgo0e.mongodb.net/discografica-db?retryWrites=true&w=majority
spring.mongodb.database=discografica-db